# Buscar usuario
GET http://localhost:8080/usuarios/todos

###
GET http://localhost:8080/usuarios/todos2

###
GET http://localhost:8080/usuarios/buscar?email=joao2@email.com
content-type: application/json 


###
POST http://localhost:8080/usuarios/criar
content-type: application/json 

{
  "nome": "Joao2",
  "email": "joao2@email.com",
  "senha": "1234"
}

###
POST http://localhost:8080/usuarios/login
content-type: application/json 

{
  "email": "joao@email.com",
  "senha": "12344"
}